FROM alpine:3.6

RUN apk add --no-cache ca-certificates

ENV DBSYNC_SERVICE_PORT 3000
ENV DBSYNC_UPDATE_PERIOD 300
ENV DBSYNC_INSERT_PERIOD 60
ENV DBSYNC_UPDATE_ROWS 5000
ENV DBSYNC_INSERT_ROWS 1000
ENV DBSYNC_START_AFTER_ID 0
ENV DBSYNC_UPDATE_TABLES ""
ENV DBSYNC_INSERT_TABLES ""
ENV DBSYNC_FILE_SYNC_COUNT 1000
ENV DBSYNC_FILE_DATA_DIR /var/lib/dbsync

ENV DBSYNC_SRC_DB_DRIVER mysql
ENV DBSYNC_SRC_DB_HOST localhost
ENV DBSYNC_SRC_DB_PORT 3306
ENV DBSYNC_SRC_DB_NAME database
ENV DBSYNC_SRC_DB_USERNAME username
ENV DBSYNC_SRC_DB_PASSWORD password
ENV DBSYNC_SRC_FILE_JSON false
ENV DBSYNC_SRC_FILE_COMPRESSION false
ENV DBSYNC_SRC_FILE_REMOVE false
ENV DBSYNC_SRC_FILE_BUCKET ""
ENV DBSYNC_SRC_FILE_ID id
ENV DBSYNC_SRC_FILE_TOPICS ""
ENV DBSYNC_SRC_FILE_EXCLUDE ""
ENV DBSYNC_SRC_FILE_SPEC ""
ENV DBSYNC_SRC_FILE_PATH ""
ENV DBSYNC_SRC_FILE_NAME ""
ENV DBSYNC_SRC_FILE_HEADER ""
ENV DBSYNC_SRC_FILE_COLUMNS ""

ENV DBSYNC_DST_DB_DRIVER mysql
ENV DBSYNC_DST_DB_HOST localhost
ENV DBSYNC_DST_DB_PORT 3306
ENV DBSYNC_DST_DB_NAME database
ENV DBSYNC_DST_DB_USERNAME username
ENV DBSYNC_DST_DB_PASSWORD password
ENV DBSYNC_DST_DB_TABLES_PREFIX ""
ENV DBSYNC_DST_DB_TABLES_POSTFIX ""
ENV DBSYNC_DST_ACCOUNT_ID id
ENV DBSYNC_DST_APP_KEY key
ENV DBSYNC_DST_FILE_JSON false
ENV DBSYNC_DST_FILE_COMPRESSION false
ENV DBSYNC_DST_FILE_BUCKET ""
ENV DBSYNC_DST_FILE_ID id
ENV DBSYNC_DST_FILE_TOPICS ""
ENV DBSYNC_DST_FILE_EXCLUDE ""
ENV DBSYNC_DST_FILE_SPEC "at:date:%s"
ENV DBSYNC_DST_FILE_PATH ""
ENV DBSYNC_DST_FILE_NAME ""
ENV DBSYNC_DST_FILE_HEADER ""
ENV DBSYNC_DST_FILE_COLUMNS ""

ENV B2_LOG_LEVEL 1

EXPOSE $DBSYNC_SERVICE_PORT

COPY bin/linux/dbsync /

CMD ["/dbsync"]
